# 绪论 {#intro}

## 研究背景

国际人力资源咨询公司怡安翰威特咨询（上海）发布《2019 人力资本研究报告》，其中 2018 年酒店行业员工离职率国内一线城市为 36.5%，二线城市高达38.8%，比零售行业的离职率高 10 个百分点左右，远高于其他大多数行业。按照这个离职率，一家公司理论上三年内员工就会整体换新一次。高离职率的背后是员工物质待遇和精神需求的双重未得到满足造成的，通过调研发现，酒店业员工对物质的追求在平均水平，离职更多的痛点是工作愉悦感和生活积极性的缺失。“你幸福吗？”是近几年社会的流行词，行业内的管理者也逐步重视员工的主观幸福感，学术界也在研究主观幸福感和领导者之间的关系，已经如何提高员工的主观幸福感。达成的一致共识是员工越来越重视自身幸福感体验，心理需要希望得到更多的满足，满足越多，幸福感体验越强，对于员工来说，愉悦的工作会给
企业带来效益的提高，企业也越来越希望通过提升员工主观幸福感来获取效益的提升[@Xu2018]。


从领导角度来讲，酒店业管理者在经营中的作用非常重要，管理者的领导方式在一定程度上会影响酒店员工的态度和行为，员工的态度和行为又进一步影响酒店的经营效益和管理目标。20 世纪以来，领导理论出现了以交易理论为主的交易型领导，以个人人格力量为主的魅力型领导，以服务为主的服务型领导，以崇高品德为主的道德型领导等理论，领导者的方式和风格与企业文化有着重要联系，高度权力集中的企业，官本位思想就会占据主要地位，令行禁止、树立权威的是其主要特点，但是高度集权意味着缺乏沟通交流，下属不能自行决定，一切行动听领导发号施令，没有自我决定权。以员工为本的企业，服务型领导为主流领导者风格，服务员工，把员工利益放到自身利益之上，处处以员工利益为主，能够调动员工资源，发挥员工的积极主动性，个人能力得到充分，同时领导愿意为其发展提供相应的资源和帮助，从而提升员工的主观幸福感。员工幸福感的提升有助于自身潜能的发挥，工作态度和行为都会发生本质上的变化，企业同时得到经济效益和社会效益的双提高，达到双赢局面[@Wang2018]。


## 研究意义

近年来国内外学者在研究领导者类型与工作绩效相关的比较多，他们更多关注的是工作层面，例如工作业绩，工作成效等等，很少涉及到员工的心理层面，对于酒店服务业员工主观幸福感的研究内容较少，将基本心理需要作为中介变量研究服务型领导与酒店员工主观幸福感的关系就更少了。本文以酒店业员工为研究对象，引入基本心理需要满足这个中介变量，来研究服务型领导和员工主观幸福感之间的作用关系，在前人研究的基础上增加了中介变量，研究基本心理需要满足在服务型领导与酒店员工主观幸福感之间的关系，探求酒店服务型领导和员工主观幸福感之间关系研究。




\newpage