# 研究结论与管理启示 {#conclusions}

## 研究结论

本文根据现有的研究，从服务型领导出发，通过成熟的量表调查，结合模型分析，检验了服务型领导与 C 酒店员工主观幸福感的主效应，以及基本心理需要满足在二者之间的中介作用。作为服务行业的典型代表，将服务型领导引入酒店管理领域，探讨其提升C酒店员工主观幸福感的路径，同时把基本心理需要作为中介变量，这是本文的创新点。根据调查结果进行数据分析，具体结论如下：首先，总体情感指数和生活满意度是酒店行业的员工主观幸福感来源。C酒店管理者的服务导向特征越高，员工的幸福指数就越高，两者有显著的正向影响。当然在调查中我们也发现，员工主观幸福感的影响因素不仅仅来源于 C 酒店领导者的风格类型，他受到生活中各种因素的影响，这也是导致我们调研的数据和设想的有些出入的原因[@Xu2018]。其次，服务型领导对C酒店员工基本心理需要满足具有显著的正向影响，服务型领导可以满足酒店员工的关系需要，有助于同级别员工之间形成比较愉快的工作气氛，人际关系的和谐、同事间的亲密关系，这些融洽的工作氛围有助于酒店员工的互助作用；服务型领导可以满足 C 酒店员工的胜任需要，可以让员工有能力学到新知识或者新技能，让员工掌握工作任务，在工作中能自己做主，同时按照自己觉得最佳的方式去工作；服务型领导可以满足 C 酒店员工的自主需要，可以让员工的工作能力得到很好地发挥，让员工相信自己能把工作做好，同时能完成工作中最困难的任务[@Wang2018]。最后，在服务型领导和酒店员工主观幸福感之间，存在着基本心理需要起着中介作用。基本心理需要中的关系需要、胜任需要和自主需要都能在服务型领导与酒店员工总体情感指数和生活满意度之间起到中介作用，进而提升酒店员工的总体情感指数和生活满意度。

## 研究局限及未来展望

第一，样本的局限性。在实证研究部分，对于样本数量、被调查者的身份都有一定的要求。在 226 份 C 酒店有效的调查问卷中，大部分受调查的酒店员工来自基层和中层，而来自高层管理人员的数据相对较少，样本的代表性稍微不足。同时，由于受新冠疫情的影响，本问卷无法去北京进行实地调研，调查问卷只能采用网络发放的形式，问卷的准确性会有一定程度的影响，同时受疫情影响，员工的物质待遇有所降低，自身的心理也有所变化，这些因素都会使主观幸福感的感受程度有所降低，对于这些不可控因素，在调查的时候都予以了提示，尽量不受外界因素的影响，公平公正的填写调查问卷。但结果的准确性仍然会有一定的影响。建议今后的样本调查中调查覆盖面更广，样本更具有普遍性，结论更具有代表性。

第二，研究的局限性。本文的研究深度和宽度仍有提升的空间，例如对于服务型领导的五个维度没有进行展开研究，每个维度对于其他变量之间的影响关系没有深入探讨，所以在未来的研究中需要进一步深入探索，重点展开服务型领导的维度分析，提升本研究的宽度和深度。

第三，领域的局限性，对于服务型领导的应用方面，除了本文探讨的酒店行业，未来的研究还可以将服务型领导的应用扩展到其他行业，例如银行业、旅行社、公共服务等领域。同时多样化的领域研究也可以给更多行业提供有价值的参考。

\newpage